m=input()
if(m=="Sunday"):
    print("yes")
if(m=="Monday"):
    print("no")
if(m=="Tuesday"):
    print("no")
if(m=="Wednesday"):
    print("no")
if(m=="Thursday"):
    print("no")
if(m=="Friday"):
    print("no")
if(m=="Saturday"):
    print("no")
